#!/bin/bash
echo "🗑️  Resetting database for fresh signup..."
echo ""
echo "This will allow you to:"
echo "  1. Sign up with a new account"
echo "  2. Go through the onboarding process"
echo "  3. Choose your study companion"
echo ""
echo "✅ Browser storage cleared (you may need to manually clear cookies)"
echo ""
echo "📝 Next steps:"
echo "  1. In your browser, press Ctrl+Shift+Del"
echo "  2. Select 'Cookies and other site data' and 'Cached images and files'"
echo "  3. Click 'Clear data'"
echo "  4. Refresh the page (F5)"
echo "  5. Sign up with a new email address"
echo ""
